"""Refuse to publish what leaks, misdeclares, or ships what it must not. Usage:
python3 tools/check_publishable.py <path>.crate | <directory> | --print-forbidden. Every tarball
check is a defect an audit found in the real 0.4.0 tarball; a version is yanked, never deleted."""
from __future__ import annotations
import pathlib, re, sys, tarfile

# THE ONE FORBIDDEN-STRING LIST: the crate tarball, the SDK mirror, the staged contract bundle and
# the Rust guard's generated fixture all read it from here. Case-insensitive SUBSTRINGS, so
# `frontpanel` catches `okFrontPanel`; each names a person, place, machine or party.
FORBIDDEN = {
    "board serial":  ["2417001"],
    "site name":     ["hangzhou", "maoming"],
    "vendor name":   ["opal", "xem7310", "frontpanel", "okfpgadataport"],
    "private repo":  ["keyvast-fpga"],
}
# The one needle no literal can express: a serial nobody has written down yet. It does not subsume
# the literal above, which also catches the known board in prose that has no `[A-Z]{2,3}` tail.
SERIAL = re.compile(r"\b24[0-9]{5}[A-Z]{2,3}\b")
# Our own module, cited on purpose. MASKED OUT OF THE LINE, never skipped, so a line that cites it
# and also leaks is still caught.
OURS = "kdi/frontpanel.py"
# The ONE sanctioned exception: dlsym resolves these byte for byte and `strings` shows them anyway.
# White-labelling, not concealment -- and it is bounded to marked blocks in the driver binding.
CARVE_FILE = "src/usb3.rs"
CARVE_BEGIN, CARVE_END = "VENDOR-NAMES-BEGIN", "VENDOR-NAMES-END"
TEXT = (".rs", ".md", ".toml", ".txt", ".json")


def carved(text: str) -> set[int]:
    """1-based line numbers inside a VENDOR-NAMES block."""
    out, depth = set(), 0
    for n, line in enumerate(text.splitlines(), 1):
        if CARVE_BEGIN in line:
            depth += 1
        if depth:
            out.add(n)
        if CARVE_END in line:
            depth = max(0, depth - 1)
    return out


def leaks(rel: str, body: str) -> list[str]:
    """`rel:line leaks a <label>` for every offending line outside a sanctioned carve-out."""
    out = []
    exempt = carved(body) if rel.endswith(CARVE_FILE) else set()
    for n, line in enumerate(body.splitlines(), 1):
        if n in exempt:
            continue
        low = line.lower().replace(OURS, "<oracle>")
        hits = {lab for lab, needles in FORBIDDEN.items() if any(s in low for s in needles)}
        if SERIAL.search(line):
            hits.add("board serial")
        out += [f"{rel}:{n} leaks a {lab}: {line.strip()[:88]}" for lab in sorted(hits)]
    return out


def scan_dir(root: pathlib.Path) -> tuple[list[str], int]:
    """The same leak scan over a TREE -- the mirrored SDK source, or the staged contract bundle.
    Fail-closed: a walk that read nothing is not a clean tree, it is a scan that checked nothing."""
    bad, seen = [], 0
    for p in sorted(root.rglob("*")):
        if not p.is_file() or p.suffix not in TEXT:
            continue
        seen += 1
        bad += leaks(str(p.relative_to(root)), p.read_text(encoding="utf-8", errors="replace"))
    if not seen:
        bad.append(f"{root} holds no {' '.join(TEXT)} file -- a scan that reads nothing certifies "
                   "nothing")
    return bad, seen


def fixture() -> str:
    """The Rust vendor-neutrality guard's needle list, generated from FORBIDDEN so that adding a
    site name is ONE edit. `<label>\\t<needle>`; that guard reads this, never its own copy."""
    return ("# GENERATED by `python3 tools/check_publishable.py --print-forbidden` -- never edit.\n"
            + "".join(f"{lab}\t{s}\n" for lab, needles in FORBIDDEN.items() for s in needles))


def refuse(bad: list[str]) -> int:
    print(f"NOT PUBLISHABLE -- {len(bad)} problem(s), each permanent once uploaded:\n")
    for b in bad:
        print(f"  * {b}")
    return 1


def main() -> int:
    if sys.argv[1:2] == ["--print-forbidden"]:
        sys.stdout.write(fixture())
        return 0
    if len(sys.argv) != 2:
        print(__doc__)
        return 2
    # A TREE, not a tarball: the mirrored SDK source and the staged contract bundle cross to the
    # public repo as directories, and until #160 the bundle crossed with no leak check at all.
    # Only the leak scan applies -- LICENSE, NOTICE and the licence expression are the tarball's.
    tree = pathlib.Path(sys.argv[1])
    if tree.is_dir():
        bad, seen = scan_dir(tree)
        if bad:
            return refuse(bad)
        print(f"PUBLISHABLE: {tree} -- {seen} text files, no identifying strings outside the "
              "sanctioned carve-out")
        return 0
    crate = tree
    if not crate.is_file():
        print(f"FAIL: {crate} does not exist -- run `cargo package` first")
        return 1

    # THE TARBALL MUST BE NEWER THAN THE SOURCE IT CLAIMS TO PACKAGE, or the gate certifies a
    # stale artifact: a .crate built 24 minutes earlier in a `.git`-less container lacked
    # `.cargo_vcs_info.json`, so 6 files passed while the 7 that upload went unexamined.
    root = crate.parent.parent.parent          # target/package/x.crate -> the crate directory
    newest, newest_f = 0.0, None
    for f in list(root.rglob("*.rs")) + list(root.glob("*.toml")) + list(root.glob("*")):
        if f.is_file() and "target" not in f.parts and f.stat().st_mtime > newest:
            newest, newest_f = f.stat().st_mtime, f
    if newest and crate.stat().st_mtime < newest:
        print(f"FAIL: {crate.name} is OLDER than {newest_f.name} -- it does not describe the "
              f"current source. Re-run `cargo package`.")
        return 1

    bad: list[str] = []
    with tarfile.open(crate) as tf:
        members = [m for m in tf.getmembers() if m.isfile()]
        names = {m.name.split("/", 1)[1] for m in members if "/" in m.name}

        # 1. the test tree must not ship
        shipped_tests = sorted(n for n in names if n.startswith("tests/"))
        if shipped_tests:
            bad.append(f"tests/ is packaged ({len(shipped_tests)} files, e.g. {shipped_tests[0]}) -- "
                       "vendor_neutral.rs exempts itself from its own scan, so this ships the very "
                       "names it exists to forbid")

        # 2. the licence obligations must ship, not merely be declared. LICENSE always; NOTICE only
        #    when there is third-party content to attribute -- demanding an empty NOTICE would teach
        #    the next person that this gate is bureaucratic rather than load-bearing.
        vendored = any(n.startswith("vendor/") and n.endswith(".bin") for n in names)
        required = ("LICENSE", "NOTICE") if vendored else ("LICENSE",)
        for f in required:
            if f not in names:
                bad.append(f"{f} is not in the tarball, but the manifest declares a licence")

        # 3. NOTICE must actually carry the embedded-Lua attribution we are obliged to reproduce
        if "NOTICE" in names:
            notice = tf.extractfile(next(m for m in members if m.name.endswith("/NOTICE"))).read().decode("utf-8", "replace")
            if "Lua.org" not in notice:
                bad.append("NOTICE does not reproduce the Lua copyright notice, which the bundled "
                           "drivers statically embed and MIT requires")

        # 4. nothing that identifies a person, place, machine or party
        for m in members:
            rel = m.name.split("/", 1)[1] if "/" in m.name else m.name
            if not rel.endswith(TEXT):
                continue
            bad += leaks(rel, tf.extractfile(m).read().decode("utf-8", "replace"))

        # 5. the licence EXPRESSION must cover what actually ships: `license` is the only
        #    machine-readable statement crates.io, docs.rs, cargo-deny and SBOMs read -- none parse
        #    NOTICE. Bare Apache-2.0 over 96% proprietary bytes drops Lua MIT, and it is IMMUTABLE.
        if vendored:
            cm = tf.extractfile(next(m for m in members if m.name.endswith("/Cargo.toml"))).read().decode("utf-8", "replace")
            lic = re.search(r'^license\s*=\s*"([^"]+)"', cm, re.M)
            expr = lic.group(1) if lic else ""
            if not expr:
                bad.append("no `license` in the packaged manifest while vendor binaries ship")
            else:
                if "LicenseRef" not in expr:
                    bad.append(f'license is "{expr}" but proprietary vendor binaries ship -- an SPDX '
                               "expression needs a LicenseRef- term for content with no SPDX id")
                if "MIT" not in expr:
                    bad.append(f'license is "{expr}" but the bundled drivers embed Lua 5.3.1 (MIT)')

        # 6. the README a customer reads must not contradict the manifest
        if "README.md" in names:
            rd = tf.extractfile(next(m for m in members if m.name.endswith("/README.md"))).read().decode("utf-8", "replace")
            for phrase, why in (("open item", "declares the licence unsettled"),
                                ("Not on crates.io", "says the crate is unpublished")):
                if phrase.lower() in rd.lower():
                    bad.append(f"README {why} -- it renders on the crates.io front page")
            for rel_link in re.findall(r"\]\((\.\./[^)]+)\)", rd):
                bad.append(f"README links outside the tarball ({rel_link}) -- 404 once rendered")

    if bad:
        return refuse(bad)
    # SAY WHAT WAS ACTUALLY CHECKED. A fixed success string is how a verdict comes to claim work it
    # did not do -- this project has already shipped one oracle that printed its pass reason on a
    # failing run. The NOTICE and licence-expression checks only apply when third-party bytes ship.
    did = [f"{len(names)} files", "tests not shipped", "LICENSE present"]
    did.append("NOTICE carries the Lua attribution" if vendored
               else "no third-party bytes, so no NOTICE owed")
    did.append("licence expression covers the vendored content" if vendored
               else "licence is ours alone")
    did += ["no identifying strings outside the sanctioned carve-out", "README consistent"]
    print(f"PUBLISHABLE: {crate.name} -- " + "; ".join(did))
    return 0


if __name__ == "__main__":
    sys.exit(main())
